### PR TITLE
Fixes to CloudMetrics

### PR DESCRIPTION
**Pull request by spono**
I fixed a couple of things in CloudMetrics and now it works.
I might try to pull some new tools more in the next days

### CODE REVIEW

**Comment by biglimp** [comment]
Great! I will merge. Please wait until I have pushed my changes on including the laz fileformat

**Comment by spono** [comment]
oh, ok...I'm quite a newbie with the PR process: shall I make another one later or what?
Thanks for your help

**Comment by biglimp** [comment]
I merged. Now you can go ahead to add new tools. Also, if you want to add 64-bit capabilities and keep the option active you just change the last input variable from False to True as the example below from line 81 in cloudmetrix.py.

`self.addParameter(QgsProcessingParameterBoolean( self.VERSION64, self.tr('Use 64-bit version'), True))`

**Comment by biglimp** [comment]
Just make sure that you have the latest commit from the repo and then just do PR and I will merge

**Comment by spono** [comment]
shall I delete my fork and re-fork yours or there's another way? I'm working from github online

**Comment by biglimp** [comment]
hm, I am not sure but if you are working with the online github you should probably refork.

**Pull request merged**
